# action.yml
name: 'TTS-PARAKEET-DUO'
description: 'Generate Engish Speech From Text'
inputs:
  text:  # id of input
    description: 'What text?'
    required: true
    default: 'World'
  content: # id of output
    required: false
    description: 'path that wave binary save to'
    default: './out.mp3'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'speaker'
  color: 'orange' 
  
