name: CI

on:
  push:
    branches: [duo-action]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: privapps/TTS-Parakeet@duo-action
        with:
          text: '1 2 3'
          content: './out.mp3'
      - run: ls -l
